import { Component } from '@angular/core';
import { MlService } from 'src/app/services/ml.service';

@Component({
  selector: 'app-predict-revenue',
  templateUrl: './predict-revenue.component.html',
  styleUrls: ['./predict-revenue.component.scss']
})
export class PredictRevenueComponent {
  year = 2025;
  month = 1;
  avg_unit_price = 0;
  total_quantity = 0;
  brand = '';
  predictionResult: number | null = null;

  brands: string[] = [
    "Fields-Gibson",
    "Beck, Hopkins and Hayes",
    "Clayton-Solis",
    "Patterson LLC",
    "Jones-Aguilar",
    "Torres-Wells",
    "Miller-Smith",
    "Deleon, Cooper and Roberts",
    "Jacobs, Obrien and Davila",
    "Lewis and Sons",
    "Hansen, Hopkins and Smith",
    "Lyons, Zuniga and Wolf",
    "Brown, Townsend and Dalton",
    "Anthony, Colon and Jimenez",
    "Walker Group",
    "Rogers-Thompson",
    "Ruiz Group",
    "Gibbs, Medina and Carter",
    "Nelson LLC",
    "Collins LLC",
    "Johnston-Jones",
    "Small-Dickerson",
    "Parker Ltd",
    "Hester LLC",
    "Hernandez-Cruz",
    "Davis, Leblanc and Ward",
    "Jensen, Russell and Thomas",
    "Gomez, Williams and Lloyd",
    "Terrell-Flynn",
    "Banks, Carter and Adkins",
    "Williams Ltd",
    "Martinez-Davis",
    "Carr Ltd",
    "Anderson, Williams and Rhodes",
    "King-Potts",
    "Massey-Robles",
    "Robinson-Walls",
    "Brewer LLC",
    "Braun-Johnson",
    "Mcdonald-Doyle",
    "Davis-Lawrence",
    "Johnson PLC",
    "Alvarado Group",
    "Harvey, Fischer and Parker",
    "Stone, Burke and Gardner",
    "Washington Group",
    "Baldwin and Sons",
    "Hernandez Inc",
    "Banks, Martinez and Walker",
    "Guerra-Lewis",
    "Ayala Inc",
    "Mendoza-Sanchez",
    "Jensen-Garcia",
    "Myers Ltd",
    "Vaughan-Dominguez",
    "Christensen LLC",
    "Johns Group",
    "Douglas-Jackson",
    "Anderson-Hawkins",
    "Craig and Sons",
    "Nelson and Sons",
    "Powers Group",
    "Castro LLC",
    "Olson LLC",
    "Stephens and Sons",
    "Pierce, Bryant and Kirk",
    "Carlson-Osborne",
    "King-Rivera",
    "Fry-Bryant",
    "Sanders, Castillo and Roberts",
    "Madden Ltd",
    "Lee, Smith and Rich",
    "Gill, Jenkins and Wilson",
    "Thompson, Wright and Ochoa",
    "Hernandez-Fry",
    "Chase, Wilson and Mueller",
    "Davila, Vega and Kim",
    "Montgomery, Davis and Warren",
    "Carr-Bird",
    "Mitchell, Doyle and Morris",
    "Davis, Martin and Peterson",
    "Allen, Smith and Gordon",
    "Miller, Oconnor and Ritter",
    "Thompson-Gibson",
    "Sanchez-Thompson",
    "Bell, Gonzalez and Burns",
    "Edwards-Green",
    "Dunn-Smith",
    "Ritter, Petersen and Brown",
    "Mcguire Inc",
    "Howell-Taylor",
    "Abbott LLC",
    "Hawkins-Hodge",
    "Smith-Howard",
    "Brown-Sawyer",
    "Davis, Oneal and Williams",
    "Shaw Ltd",
    "Burnett Group",
    "Jones Ltd",
    "Garrett-Burns",
    "Williamson Group",
    "Adams-Ellison",
    "Tran-Wall",
    "Sullivan-Nunez",
    "Lowe-Lamb",
    "Steele-Vincent",
    "Taylor LLC",
    "Davidson, Carter and Walton",
    "Juarez Inc",
    "Salas, Walker and Kelley",
    "Ryan, Martinez and Williamson",
    "Rangel, Vega and Jenkins",
    "Levy PLC",
    "Alexander-Gaines",
    "Williams LLC",
    "Green Ltd",
    "Thompson-Peterson",
    "Jordan Ltd",
    "Carpenter, Smith and White",
    "Jimenez Ltd",
    "Mclean PLC",
    "Wilkins Ltd",
    "Nelson Ltd",
    "Smith LLC",
    "Austin, Lara and Barker",
    "Berger LLC",
    "Knapp, Briggs and Gordon",
    "Oneill, Hamilton and Peck",
    "Jones-Young",
    "Farmer Group",
    "Ramirez Ltd",
    "Edwards, Campos and Berry",
    "Simmons and Sons",
    "Brown-Neal",
    "Garner-Hopkins",
    "Jackson Inc",
    "Villanueva, Miles and Estrada",
    "Hendrix-Foster",
    "Hayden-Ramsey",
    "Smith-Jones",
    "Bruce PLC",
    "Santiago-Fields",
    "Lewis-Weber",
    "Martinez and Sons",
    "Mcdonald-Tucker",
    "Lindsey Ltd",
    "Washington Inc",
    "Bridges PLC",
    "Cox and Sons",
    "Thornton Inc",
    "Meyers, Sharp and Miller",
    "Perez-Watkins",
    "Fleming Ltd",
    "Lewis, Gomez and Pena",
    "Coffey-Stout",
    "Petersen-Green",
    "Perez Inc",
    "Green-Munoz",
    "Fowler-Parrish",
    "Hughes LLC",
    "Pearson-Smith",
    "Rodriguez, Smith and Mason",
    "Howard-Cummings",
    "Wright Ltd",
    "Davis Inc",
    "Burke, Hardy and Adams",
    "Williams Inc",
    "Goodman Ltd",
    "Warren, Garza and Williams",
    "Gomez Inc",
    "Fry-Benson",
    "Moore, Carter and Li",
    "Robinson Inc",
    "Riley Ltd",
    "Allen LLC",
    "Steele-Mitchell",
    "Clark, Burke and Wilson",
    "Hernandez, Strong and Flores",
    "Montes-Gibson",
    "Martinez, Williamson and Byrd",
    "Mitchell, Wilson and Adams",
    "Hughes-Martinez",
    "Peters-Watson",
    "Hays-Berry",
    "Holden PLC",
    "Williams-Brewer",
    "Brown-Nelson",
    "Jackson, Nielsen and Morris",
    "Davis, Hull and Payne",
    "Maxwell-Lopez",
    "Lee-Martin",
    "Schultz, Johnson and Klein",
    "Hawkins Ltd",
    "Hernandez-Rodriguez",
    "Odonnell, Richardson and George",
    "Hampton LLC",
    "Gray, Martinez and Hernandez",
    "Williams, Hill and Taylor",
    "Bates Group",
    "Glover-Barrett"
  ];
  
  constructor(private mlService: MlService) {}

  predictRevenue() {
    const data = {
      year: this.year,
      month: this.month,
      avg_unit_price: this.avg_unit_price,
      total_quantity: this.total_quantity,
      brand: this.brand
    };

    this.mlService.predictRevenue(data).subscribe({
      next: (res) => this.predictionResult = Number(res),
      error: (err) => alert('Prediction failed: ' + err.message)
    });
  }
}
